### ISSUE TITLE
Hoover search - replace nomad.get_address() with a consul dns address

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/node#111]
Right now, when creating a collection, the `deploy` command runs a [management command](https://github.com/hoover/search/blob/4578096403d52331b97540ba1f9d246c8d4c2666/hoover/search/management/commands/addcollection.py) in hoover-search, to register the new collection. It uses `nomad.get_address()` to get the current address of the nomad server, which is fragile, since it may change.

We should use `something.service.consul` instead, which points to [Consul DNS](https://www.consul.io/docs/agent/dns.html). The `something` should point to [this fabio task](https://github.com/liquidinvestigations/node/blob/8514250ef9c6bb72a6b53af2072b1be05621610f/templates/hoover-system.nomad#L9) which currently doesn't defiine a service but it should.

**Comment by gabriel-v** [comment]
we ended up with no DNS - just expose the same list of ports/paths on all hosts using fabio
