### ISSUE TITLE
script importfromdockersetup asks to remove collections from liquid.ini

### ISSUE THREAD

**Issue by MattesR** [liquidinvestigations/node#113]
But there are collections in the default config. At least exclude uploads from the check, maybe also testdata

**Comment by MattesR** [comment]
Also, `liquid.ini` is rebuilt without any comments and `upload` is not part of the new ini file.

**Comment by mgax** [comment]
I think the import script should not touch liquid.ini at all. It could say, for example, "please add these lines to your liquid.ini and press enter".

**Comment by MattesR** [comment]
I agree. It also removes all comments and therefore explanations of what's going on. I'll assign @mugurrus
