### ISSUE TITLE
Remove `./liquid.py nomad_address`

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/node#15]
It returns the address advertised by nomad when talking to other nomad servers. With [cluster](https://github.com/liquidinvestigations/cluster), by default, this is `127.0.0.1`. It has nothing to do with the address where services accept traffic, which is more like ```{{ GetInterfaceIP `eth0` }}```.

We should get rid of this command, it was a quick hack to make `/liquid.py shell hoover-search ./manage.py addcollection ...` work for the readme. Instead hoover-search should discover collections within the same cluster and not expect the operator to run `addcollection` manually.

**Comment by gabriel-v** [comment]
outdated
