### ISSUE TITLE
VagrantPlugins::Vmck::Config: image_path setting shouldn't exist

### ISSUE THREAD

**Issue by raduklb** [liquidinvestigations/node#182]
When running `vagrant up --provider=vmck`, the command issues:
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

VagrantPlugins::Vmck::Config:
* The following settings shouldn't exist: image_path
```
By removing the line where `vmck.image_path` is set in `Vagrantfile` I was able to bypass this problem, but I don't think this is the expected behaviour.
OS: macOS 10.14.5

**Comment by mgax** [comment]
> * The following settings shouldn't exist: image_path

You're using an old version of `vagrant-vmck`. Update it (`vagrant plugin update vmck`) and the error should go away.
