### ISSUE TITLE
Document the vault-related setup in readme

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/node#36]
* run `./liquid initializevault`
* set vault token (and optionally unseal key) in `liquid.ini`:
    ```ini
    [cluster]
    vault_key = 20428448bdd81f4619775ea41143684f9cea7f489c17445ea5722f8f11621957
    vault_token = s.j0HN9V6fc1H0A7hPSb2LBpUh
    ```
* run `./liquid unsealvault`

**Comment by gabriel-v** [comment]
liquidinvestigations/cluster now runs `autovault` before booting.
