### ISSUE TITLE
Refactor crowbar.py/liquid.py script to use requests

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/node#5]
Replace [the JsonApi class](https://github.com/liquidinvestigations/node/blob/ddbb1350276287e28d60cfb0875cda33e4a7795f/nomad/crowbar.py#L42) with calls to `request.put(url, json=payload)`

**Comment by mgax** [comment]
I just realized, this would add a dependency to the requests library. This means we have to create a virtualenv and install dependencies before we can use the script. I think it's a great advantage to rely only on the standard library.
