### ISSUE TITLE
debug=false is true?

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/node#68]
This config seems to enable debugging, maybe because `"false"` is a truthy string?

```ini
[liquid]
debug = false
```

**Comment by gabriel-v** [comment]
In what app?

That value gets read here: https://github.com/liquidinvestigations/node/blob/c24a1c675afea8a7225217f31fd4143be1c78f0c/liquid_node/configuration.py#L43

**Comment by mgax** [comment]
Ok, maybe I misunderstood what I was seeing, sorry.
