### ISSUE TITLE
Restrict nextcloud domain

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/node#88]
So that users can't be tricked into loading our nextcloud under a different domain. It's standard webapp security practice.

It looks like this can be achieved with two changes:
1. The environment variable `NEXTCLOUD_TRUSTED_DOMAINS = nextcloud.{{ key "liquid_domain" }}`;
2. Running `sudo -u www-data ./occ config:system:set --value=nextcloud.liquiddemo.org overwritehost` in the nextcloud container.

**Comment by gabriel-v** [comment]
the oauth2 proxy will take care of verifying host/domain
