### ISSUE TITLE
Attribute Error when migrating from docker setup.

### ISSUE THREAD

**Issue by MattesR** [liquidinvestigations/node#97]
I wanted to test the migration from a docker-compose based hoover instance to a hoover instance in the nomad cluster.
I've created the collections from the old hoover in `liquid.ini` (decapitalizing the letters) and copied their blobs and the pg data folder into the respective directories.
I also copied the elastic search index and the pg database of hoover into the respective directories.
I get an error when I try to access the collections in the admin-interface of search (see screenshot)
![Error in serch admin interface migration](https://user-images.githubusercontent.com/42345537/59425453-42845f80-8dd6-11e9-82d6-5b09f435d61a.png)

**Comment by gabriel-v** [comment]
We forgot to rename one of the keys when migrating from django 1 to django 2 -- see https://github.com/hoover/search/pull/66
